"""Part 2: m05-m09 (CDS, DB, OData, CRUD, business logic)."""
from common import mod, step_mod, layer, callout, code, table, grid, steps, qa, quiz, mermaid, depth, adr

def build():
    parts = []

    b = []
    b.append(layer("What is it?"))
    b.append(depth(simple="CDS is the blueprint of your business: what things exist (Supplier, Order) and how they relate — before any screens or code.", sap="CDS compiles to OData V4 + SQL. One model drives the API, the DB schema, and Fiori annotations.", technical="Namespace + entities + associations/compositions + managed/cuid aspects + types + @assert constraints. Compositions own children (items die with parent); associations reference independent entities."))
    b.append(code("cds", "db/common.cds — reusable types (real db/common.cds)", "namespace procurement.common;\n\naspect TenantAware { tenantId : String(64); }\naspect Auditable { createdByAgent : String(128); lastModifiedByAgent : String(128); }\ntype RiskLevel : String enum { LOW; MEDIUM; HIGH; CRITICAL; }\ntype PRStatus : String enum { DRAFT; SUBMITTED; UNDER_REVIEW; APPROVED; REJECTED; CONVERTED_TO_PO; CANCELLED; }\ntype POStatus : String enum { DRAFT; PENDING_APPROVAL; APPROVED; SENT_TO_SUPPLIER; PARTIALLY_RECEIVED; FULLY_RECEIVED; INVOICED; CLOSED; CANCELLED; }\ntype ApprovalStatus : String enum { PENDING; APPROVED; REJECTED; ESCALATED; CANCELLED; }\ntype InvoiceStatus : String enum { DRAFT; SUBMITTED; MATCHED; MISMATCH; APPROVED; PAID; REJECTED; CANCELLED; }\ntype PaymentStatus : String enum { PENDING; PROCESSING; COMPLETED; FAILED; CANCELLED; }\ntype PolicyAction : String enum { AUTO_APPROVE; REQUIRE_MANAGER; REQUIRE_FINANCE; REQUIRE_HUMAN; DENY; }\ntype ActorType : String enum { USER; AGENT; SYSTEM; }\ntype MessageRole : String enum { USER; ASSISTANT; TOOL; SYSTEM; }\ntype ToolExecutionStatus : String enum { PENDING; RUNNING; SUCCESS; FAILED; DENIED; }"))
    b.append(code("cds", "db/schema.cds — core documents (matches repo)", "namespace procurement.db;\nusing { cuid, managed } from '@sap/cds/common';\nusing { procurement.common as c } from './common';\n\nentity Suppliers : cuid, managed, c.TenantAware {\n  supplierId : String(64) not null;\n  name       : String(256) not null;\n  active     : Boolean default true not null;\n  riskScore  : Integer default 0;\n  riskLevel  : c.RiskLevel default #LOW;\n  onTimeRate : Decimal(5,2) default 100.0;\n  contacts   : Composition of many SupplierContacts on contacts.supplier = $self;\n}\n\nentity PurchaseRequisitions : cuid, managed, c.TenantAware, c.Auditable {\n  requisitionNo : String(32) @assert.unique not null;\n  title         : String(256) not null;\n  requester     : Association to Users not null;\n  department    : Association to Departments not null;\n  status        : c.PRStatus default #DRAFT not null;\n  totalAmount   : Decimal(18,2) default 0 not null;\n  version       : Integer default 1 not null; // optimistic concurrency\n  items         : Composition of many PurchaseRequisitionItems on items.requisition = $self;\n  approvals     : Association to many Approvals on approvals.requisition = $self;\n}\n\nentity PurchaseOrders : cuid, managed, c.TenantAware, c.Auditable {\n  orderNo     : String(32) @assert.unique not null;\n  requisition : Association to PurchaseRequisitions;\n  supplier    : Association to Suppliers not null;\n  status      : c.POStatus default #DRAFT not null;\n  totalAmount : Decimal(18,2) default 0 not null;\n  version     : Integer default 1 not null;\n  items       : Composition of many PurchaseOrderItems on items.purchaseOrder = $self;\n}"))
    b.append(table(["Concept", "Used where", "Why"], [["cuid, managed", "Every entity", "UUID key + createdAt/modifiedAt/createdBy free"], ["Composition", "PR-items, PO-items, contacts, messages", "Children owned; cascade delete"], ["Association", "supplier, requester, department", "Independent master data referenced"], ["version Integer", "PR + PO", "Optimistic concurrency: WHERE version = expected"], ["@assert.unique", "requisitionNo, orderNo, supplierId", "DB-level duplicate guard"]]))
    b.append(code("bash", "Test it", "npx cds compile --to csn db srv   # must exit 0 after every CDS change"))
    b.append(callout("prod", "Production note", "<p>HANA Cloud needs no model change — only the <code>db.kind</code> + deploy target change (Phase 6). Keep CDS portable: no Postgres-only types.</p>"))
    parts.append(step_mod("m05", "05", "Phase 2 — Domain model with CDS", "WHAT WE HAVE: empty db/. ADDING NOW: 30+ entities with compositions, tenant isolation, status enums, concurrency versions.", "\n".join(b)))

    b = []
    b.append(layer("The ladder: SQLite → Postgres → HANA"))
    b.append(mermaid("FIG. 2 — SAME CDS, THREE DATABASES", """flowchart TD
  CDS["CDS model"] --> ADP["CAP db adapter"]
  ADP --> LITE["SQLite in-memory (tests)"]
  ADP --> PG["PostgreSQL (local dev)"]
  ADP --> HANA["HANA Cloud (prod)"]
  PG --> DOCKER["docker compose service db"]"""))
    b.append(code("json", "package.json — cds.requires.db (real shape)", '{\n  "cds": { "requires": {\n    "db": { "kind": "sqlite", "credentials": { "database": ":memory:" },\n      "[production]": { "kind": "postgres" },\n      "[postgres]": { "kind": "postgres", "pool": { "min": 0, "max": 5 } } },\n    "auth": { "kind": "mocked", "[production]": { "kind": "jwt" } } } }\n}'))
    b.append(code("yaml", "docker-compose.yml — local Postgres", 'services:\n  db:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: procurement\n      POSTGRES_USER: postgres\n      POSTGRES_PASSWORD: changeme\n    ports:\n      - "5432:5432"\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    healthcheck:\n      test: ["CMD-SHELL", "pg_isready -U postgres"]\n      interval: 5s\n      retries: 10\n\n  app:\n    build: .\n    depends_on:\n      db:\n        condition: service_healthy\n    environment:\n      PORT: 4004\n      DATABASE_URL: postgresql://postgres:changeme@db:5432/procurement\n      ALLOW_MOCK_AUTH: "true"\n      JWT_SECRET: dev-only-secret-change-me\n    ports:\n      - "4004:4004"\n\nvolumes:\n  pgdata:'))
    b.append(code("bash", "Run it", "docker compose up -d db\n# .env (never commit real secrets):\n# DATABASE_URL=postgresql://postgres:changeme@localhost:5432/procurement\nnpm run db:deploy:pg   # node scripts/deploy-pg.cjs\nnpm start               # cds serve under tsx"))
    b.append(callout("mistake", "Common mistake", "<p>Bare <code>tx.read().where()</code> returns an <b>array</b> — <code>.status</code> on it is <code>undefined</code>. Single-row reads MUST use <code>SELECT.one</code>. The repo's handlers already do.</p>"))
    b.append(table(["Environment", "Database", "What changes", "What stays identical"], [["Test", "SQLite memory", "Nothing to install", "CDS + handlers"], ["Local dev", "Postgres Docker", "cds profile + DATABASE_URL", "CDS + handlers + seed"], ["Production", "HANA Cloud", "mta.yaml service + deploy", "CDS + handlers (portable)"]]))
    parts.append(step_mod("m06", "06", "Phase 3 — Database", "HAVE: CDS model. ADDING: runnable database with an upgrade path that never rewrites business code.", "\n".join(b)))

    b = []
    b.append(layer("What is it?"))
    b.append('<p>OData V4 is the typed HTTP contract CAP generates from your service definition: entities become URL-addressable sets with $filter/$expand/$orderby, actions become POST endpoints. Our paths: <code>/odata/v4/procurement</code>, <code>/catalog</code>, <code>/supplier</code>, <code>/invoice</code>, <code>/approval</code>, <code>/mcp</code>, <code>/agents</code>.</p>')
    b.append(code("cds", "srv/procurement-service.cds (real file)", "using { procurement.db as db } from '../db/schema';\n\n@path: '/odata/v4/procurement'\n@odata\n@mcp: 'procurement-ops'\nservice ProcurementService {\n  entity PurchaseRequisitions as projection on db.PurchaseRequisitions;\n  entity PurchaseRequisitionItems as projection on db.PurchaseRequisitionItems;\n  entity PurchaseOrders as projection on db.PurchaseOrders;\n  entity PurchaseOrderItems as projection on db.PurchaseOrderItems;\n  entity GoodsReceipts as projection on db.GoodsReceipts;\n\n  action submitRequisition(ID : String) returns String;\n  action approveRequisition(ID : String, comment : String) returns String;\n  action rejectRequisition(ID : String, comment : String) returns String;\n  action convertToPurchaseOrder(requisitionID : String, supplierID : String) returns PurchaseOrders;\n}"))
    b.append(callout("warn", "ID params are String, not UUID", "<p>OData URL parsing nulls non-GUID values for UUID-typed params → phantom 404s with readable seed IDs. This repo types every action/function ID param as <code>String</code> deliberately. OData <b>function</b> params need parenthesis syntax <code>/fn(p='v')</code>, never <code>?p='v'</code>.</p>"))
    b.append(code("bash", "Test it (mocked auth, see Phase 7)", "curl -H 'x-mock-user: buyer:EMPLOYEE' http://localhost:4004/odata/v4/procurement/PurchaseRequisitions\ncurl -H 'x-mock-user: buyer:EMPLOYEE' 'http://localhost:4004/odata/v4/procurement/PurchaseRequisitions?$filter=status%20eq%20%27DRAFT%27&$top=5'"))
    b.append(table(["Verb", "Example", "Meaning"], [["GET", "/PurchaseRequisitions", "List (tenant-filtered)"], ["GET", "/PurchaseRequisitions(ID)", "One row + $expand=items"], ["POST", "/PurchaseRequisitions", "Create (before CREATE validates)"], ["PATCH", "/PurchaseRequisitions(ID)", "Partial update (version-checked)"], ["POST", "/submitRequisition", "Unbound action via .send(), never .run({action}) cross-service"]]))
    parts.append(step_mod("m07", "07", "Phase 4 — OData V4 service", "HAVE: tables. ADDING: typed HTTP API with actions for every state change.", "\n".join(b)))

    b = []
    b.append(layer("CAP already gives you CRUD — customize at the edges"))
    b.append('<p>Generic handlers serve CREATE/READ/UPDATE/DELETE. You add <code>before/after</code> hooks only for validation, defaults, tenancy and audit. State changes (submit/approve/convert) are <b>actions</b>, not raw PATCHes, so transitions are explicit and auditable.</p>')
    b.append(code("typescript", "srv/procurement-service.ts — guards (real pattern)", "export default class ProcurementService extends (cds.ApplicationService as any) {\n  async init() {\n    const { PurchaseRequisitions } = this.entities;\n    this.before('READ', PurchaseRequisitions, async (req: any) => {\n      const ctx = await ctxOf(req);                       // x-mock-user locally, JWT in prod\n      AuthorizationService.requirePermission(ctx, PERMISSIONS.READ_PR);\n      req.query.where({ tenantId: ctx.tenantId });       // tenant isolation, always\n    });\n    this.before(['CREATE'], PurchaseRequisitions, async (req: any) => {\n      const ctx = await ctxOf(req);\n      AuthorizationService.requirePermission(ctx, PERMISSIONS.CREATE_PR);\n      validateRequisition(req.data);                      // quantity > 0, amounts sane\n      req.data.tenantId = ctx.tenantId;                   // never trust client tenant\n      req.data.status = 'DRAFT';\n      req.data.requisitionNo ??= `PR-${Date.now().toString().slice(-6)}`;\n    });\n    this.after(['CREATE'], PurchaseRequisitions, async (data: any, req: any) => {\n      try { if (data) await writeAudit(/* ... */); }      // audit must never break response\n      catch (e) { console.error('[audit] hook failed', (e as Error).message); }\n      return data;                                        // after-hooks returning undefined WIPE the response\n    });\n    return super.init();\n  }\n}"))
    b.append(table(["Hook", "Use for", "Never for"], [["before CREATE/UPDATE", "Validation, defaults, tenant stamping, permission check", "Cross-entity writes (use actions + tx)"], ["after CREATE", "Audit, notifications (try/catch, return data)", "Throwing — it would break the response"], ["on <action>", "State transitions with tx + version check + audit", "Silent PATCH status edits"]]))
    b.append(callout("mistake", "after-hook trap", "<p>An <code>after</code> hook that returns <code>undefined</code> wipes the response body. Always <code>return data</code>. Wrap audit in try/catch — observability must never break the business path.</p>"))
    parts.append(step_mod("m08", "08", "Phase 5 — Complete CRUD", "HAVE: OData surface. ADDING: validation, tenancy, RBAC and audit on every read/write.", "\n".join(b)))

    b = []
    b.append(layer("Business logic: submit → approve → convert"))
    b.append(mermaid("FIG. 3 — REQUISITION LIFECYCLE WITH POLICY GATE", """flowchart TD
  D["DRAFT"] --> S["SUBMITTED"]
  S --> U["UNDER_REVIEW"]
  U --> A["APPROVED"]
  U --> R["REJECTED"]
  A --> C["CONVERTED_TO_PO"]
  A --> POL{"Policy gate + budget check"}
  POL -->|"AUTO_APPROVE"| PO["INSERT PurchaseOrder + items"]
  POL -->|"REQUIRE_HUMAN + agent caller"| DENY["403 POLICY_REQUIRES_HUMAN_APPROVAL"]
  POL -->|"DENY"| DENY2["403 FORBIDDEN"]"""))
    b.append(code("typescript", "convertToPurchaseOrder — tx + budget + policy + audit (real logic)", "this.on('convertToPurchaseOrder', async (req: any) => {\n  try {\n    const ctx = await ctxOf(req);\n    AuthorizationService.requirePermission(ctx, PERMISSIONS.CREATE_PO);\n    const tx = cds.tx(req);                               // single tx for all writes\n    const pr: any = await tx.run(SELECT.one.from(PurchaseRequisitions)\n      .where({ ID: req.data.requisitionID, tenantId: ctx.tenantId }).forUpdate());\n    const supplier: any = await tx.run(SELECT.one.from('procurement.db.Suppliers')\n      .where({ ID: req.data.supplierID, tenantId: ctx.tenantId }));\n    validatePO(pr, supplier);\n    const budget: any = await tx.run(SELECT.one.from('procurement.db.Budgets')\n      .where({ department_ID: pr.department_ID, tenantId: ctx.tenantId }).orderBy({ fiscalYear: 'desc' }));\n    if (budget) {\n      const avail = Number(budget.totalAmount) - Number(budget.committed) - Number(budget.consumed);\n      if (Number(pr.totalAmount) > avail) throw reqError('BUDGET_EXCEEDED', `need ${pr.totalAmount}, have ${avail}`);\n    }\n    const decision = evaluatePolicy({ amount: Number(pr.totalAmount), riskLevel: supplier.riskLevel },\n      await tx.read('procurement.db.Policies').where({ tenantId: ctx.tenantId, active: true }));\n    if (decision.action === 'REQUIRE_HUMAN' && ctx.isAgent)\n      throw reqError('POLICY_REQUIRES_HUMAN_APPROVAL', `Policy ${decision.code} needs a human`);\n    if (decision.action === 'DENY') throw reqError('FORBIDDEN', `Policy ${decision.code} denies this order`);\n    // ... INSERT PO + copy items, mark PR CONVERTED_TO_PO, writeAudit ...\n  } catch (e) { req.reject(toHttpError(e)); }\n});"))
    b.append(table(["req object", "Contains", "Example use"], [["req.data", "Action/entity payload", "IDs, comment, amounts"], ["req.user (via ctx)", "Authenticated identity", "userId, roles, tenantId, isAgent"], ["cds.tx(req)", "Request-scoped transaction", "All-or-nothing multi-table writes"], ["SELECT.one + forUpdate()", "Locked single row", "Prevents double-approve races"]]))
    b.append(adr("001", "Policy decides, LLM recommends", "Agents propose amounts and suppliers; someone must have the final deterministic word.", "Who enforces spend/risk rules?", [("Prompt-only rules", "Bypassed by rephrasing; unauditable."), ("DB-driven policy engine", "Versioned, testable, deterministic, auditable.")], "evaluatePolicy() over Policies table runs inside the converting transaction; agents cannot skip it.", "DB policy evaluation is deterministic and tenant-scoped; prompts stay advisory.", "Extra read per conversion; policy authors need a review workflow.", "Every convert call carries a policy decision + audit row; changing a threshold is a data change, not a deploy."))
    parts.append(step_mod("m09", "09", "Phase 6 — Business logic + transactions", "HAVE: guarded CRUD. ADDING: lifecycle actions that are transactional, concurrency-safe, budget- and policy-gated.", "\n".join(b)))

    return parts
