export const PERMISSIONS = {
  READ_PR: 'READ_PURCHASE_REQUISITION',
  CREATE_PR: 'CREATE_PURCHASE_REQUISITION',
  UPDATE_PR: 'UPDATE_PURCHASE_REQUISITION',
  DELETE_PR: 'DELETE_PURCHASE_REQUISITION',
  APPROVE_PR: 'APPROVE_PURCHASE_REQUISITION',
  REJECT_PR: 'REJECT_PURCHASE_REQUISITION',
  CREATE_PO: 'CREATE_PURCHASE_ORDER',
  UPDATE_PO: 'UPDATE_PURCHASE_ORDER',
  CANCEL_PO: 'CANCEL_PURCHASE_ORDER',
  READ_SUPPLIER: 'READ_SUPPLIER',
  CREATE_SUPPLIER: 'CREATE_SUPPLIER',
  UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
  CREATE_INVOICE: 'CREATE_INVOICE',
  READ_INVOICE: 'READ_INVOICE',
  APPROVE_INVOICE: 'APPROVE_INVOICE',
  READ_BUDGET: 'READ_BUDGET',
  UPDATE_BUDGET: 'UPDATE_BUDGET',
  EXECUTE_AGENT: 'EXECUTE_AGENT',
  EXECUTE_MCP_TOOL: 'EXECUTE_MCP_TOOL',
  VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',
  ADMIN_SYSTEM: 'ADMIN_SYSTEM',
} as const;

export const ROLES = {
  ADMIN: 'ADMIN',
  PROCUREMENT_MANAGER: 'PROCUREMENT_MANAGER',
  PROCUREMENT_OFFICER: 'PROCUREMENT_OFFICER',
  APPROVER: 'APPROVER',
  FINANCE: 'FINANCE',
  SUPPLIER_MANAGER: 'SUPPLIER_MANAGER',
  AUDITOR: 'AUDITOR',
  EMPLOYEE: 'EMPLOYEE',
  AI_AGENT: 'AI_AGENT',
} as const;

// Static role -> permissions map (bootstrapped into DB; enforced at runtime from DB when available).
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  ADMIN: Object.values(PERMISSIONS),
  PROCUREMENT_MANAGER: [
    PERMISSIONS.READ_PR, PERMISSIONS.CREATE_PR, PERMISSIONS.UPDATE_PR,
    PERMISSIONS.APPROVE_PR, PERMISSIONS.REJECT_PR,
    PERMISSIONS.CREATE_PO, PERMISSIONS.UPDATE_PO, PERMISSIONS.CANCEL_PO,
    PERMISSIONS.READ_SUPPLIER, PERMISSIONS.CREATE_SUPPLIER, PERMISSIONS.UPDATE_SUPPLIER,
    PERMISSIONS.CREATE_INVOICE, PERMISSIONS.READ_INVOICE,
    PERMISSIONS.READ_BUDGET, PERMISSIONS.EXECUTE_AGENT, PERMISSIONS.EXECUTE_MCP_TOOL,
  ],
  PROCUREMENT_OFFICER: [
    PERMISSIONS.READ_PR, PERMISSIONS.CREATE_PR, PERMISSIONS.UPDATE_PR,
    PERMISSIONS.CREATE_PO, PERMISSIONS.UPDATE_PO,
    PERMISSIONS.READ_SUPPLIER, PERMISSIONS.CREATE_SUPPLIER,
    PERMISSIONS.CREATE_INVOICE, PERMISSIONS.READ_INVOICE,
    PERMISSIONS.READ_BUDGET, PERMISSIONS.EXECUTE_AGENT, PERMISSIONS.EXECUTE_MCP_TOOL,
  ],
  APPROVER: [
    PERMISSIONS.READ_PR, PERMISSIONS.APPROVE_PR, PERMISSIONS.REJECT_PR,
    PERMISSIONS.READ_SUPPLIER, PERMISSIONS.READ_BUDGET, PERMISSIONS.READ_INVOICE,
  ],
  FINANCE: [
    PERMISSIONS.READ_PR, PERMISSIONS.READ_INVOICE, PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.APPROVE_INVOICE, PERMISSIONS.READ_BUDGET, PERMISSIONS.UPDATE_BUDGET,
    PERMISSIONS.READ_SUPPLIER,
  ],
  SUPPLIER_MANAGER: [
    PERMISSIONS.READ_SUPPLIER, PERMISSIONS.CREATE_SUPPLIER, PERMISSIONS.UPDATE_SUPPLIER,
    PERMISSIONS.READ_PR,
  ],
  AUDITOR: [PERMISSIONS.READ_PR, PERMISSIONS.READ_INVOICE, PERMISSIONS.READ_BUDGET, PERMISSIONS.READ_SUPPLIER, PERMISSIONS.VIEW_AUDIT_LOG],
  EMPLOYEE: [PERMISSIONS.READ_PR, PERMISSIONS.CREATE_PR, PERMISSIONS.UPDATE_PR, PERMISSIONS.READ_SUPPLIER, PERMISSIONS.READ_BUDGET],
  AI_AGENT: [], // agents get explicit per-agent grants only — never wildcard
};

export const MCP_TOOL_PERMISSIONS: Record<string, string> = {
  searchPurchaseRequisitions: PERMISSIONS.READ_PR,
  getPurchaseRequisition: PERMISSIONS.READ_PR,
  createPurchaseRequisition: PERMISSIONS.CREATE_PR,
  searchPurchaseOrders: PERMISSIONS.READ_PR,
  getPurchaseOrder: PERMISSIONS.READ_PR,
  getSupplier: PERMISSIONS.READ_SUPPLIER,
  searchSuppliers: PERMISSIONS.READ_SUPPLIER,
  checkBudget: PERMISSIONS.READ_BUDGET,
  getInvoiceStatus: PERMISSIONS.READ_INVOICE,
  getApprovalStatus: PERMISSIONS.READ_PR,
  getProcurementRisk: PERMISSIONS.READ_PR,
  createPurchaseOrder: PERMISSIONS.CREATE_PO,
  submitForApproval: PERMISSIONS.CREATE_PR,
  getRemoteSuppliers: PERMISSIONS.READ_SUPPLIER,
  getRemoteLogisticsIntel: PERMISSIONS.READ_SUPPLIER,
};
